service: merge-lock-queue-service

provider:
  profile: ml-serverless
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"

custom:
  writeEnvVars:
    STAGE: ${opt:stage}
    DEV_USER_SERVICE_API_ID: ${file(../env_vars.yml):DEV_USER_SERVICE_API_ID}

    PROD_USER_SERVICE_API_ID: ${file(../env_vars.yml):PROD_USER_SERVICE_API_ID}

plugins:
  - serverless-plugin-write-env-vars

resources:
  Resources:
    userEventsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'merge-lock-${opt:stage}'

functions:
  add:
    handler: handler.add
    events:
      - http:
          path: mergelock/add/
          method: post

  list:
    handler: handler.list
    events:
      - http:
          path: mergelock/list
          method: get

  remove:
    handler: handler.remove
    events:
      - http:
          path: mergelock/remove/
          method: post

  pop:
    handler: handler.pop
    events:
      - http:
          path: mergelock/pop/{username}
          method: get

  back:
    handler: handler.back
    events:
      - http:
          path: mergelock/back
          method: post

